In [1]:
import tensorflow as tf
import numpy as np

# Tensor
Tensors are the multidimensional arrays with uniform type called as dtype. All the tensors are immutable like python strings and numbers. Tensors cannot be updated once created but can be created new onces.

In [2]:
#checking supported dtypes of tensorflow
print(tf.dtypes.DType)

<class 'tensorflow.python.framework.dtypes.DType'>


In [3]:
#Lets create some tensors
#All the things in tensorflow are tensors. Tensors are always matrices.
# Scalar is Rank-0 tensor

In [4]:
scalar = tf.constant(4) #This will be int32 dtype default
print(scalar)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
#A vector is rank-1 tensor
vector = tf.constant([1 ,2,3,4]) #default dtype-> int32
print(vector)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [6]:
#creating vector with dtype float16
vector16 = tf.constant([1,2,3,4] , dtype=tf.float16)
print(vector16)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float16)


In [7]:
# A matrix is rank-3 tensor
matrix = tf.constant([ [1,2,3] , [4,5,6] , [7,8,8]]) #int32
print(matrix)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 8]], shape=(3, 3), dtype=int32)


# Shapes
Tensors have shapes.
Tensor shape dictionary :
Shape : The length of each of dimensions
Rank : The number of tensor dimensions eg: scalar is rank-0 , vector is rank-1 matrix is rank-2 and so on
Axis : A particular dimension of tensor 
Size : total number of items in tensor

In [8]:
#working with shapes 
matrix = tf.constant([[1,2,3] , [4,5,6] , [7,8,9]])
print('Our matrix ->',matrix)
print('Shape of matrix',matrix.shape)

Our matrix -> tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
Shape of matrix (3, 3)


In [9]:
print('dimension : ',matrix.ndim)  

dimension :  2


In [10]:
print('rank:' , tf.size(matrix).numpy()) #total number of items in tensor 3*3

rank: 9


# Indexing

#Rules for Indexing
1. They are similar to Python
2. Indexing start from 0
3. Negative indexing starts from end
4. colon : are used for slicing

In [11]:
vector = tf.constant([1,2,3,4,5])
print('Original vector ' , vector.numpy())
print('3rd element : ', vector[2])
print('last element : ',vector[-1])

Original vector  [1 2 3 4 5]
3rd element :  tf.Tensor(3, shape=(), dtype=int32)
last element :  tf.Tensor(5, shape=(), dtype=int32)


In [12]:
matrix  = tf.constant(matrix)
print('original matrix : ',matrix)
print('element at 1st row and 2th col =>',matrix[0,1])

original matrix :  tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
element at 1st row and 2th col => tf.Tensor(2, shape=(), dtype=int32)


# Reshaping matrix

In [13]:
#original mat
mat = tf.constant([ [ 1,2,3,4] , [5,6,7,8]])
print(mat,'\n')
print('shape of mat: ' , mat.shape)

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32) 

shape of mat:  (2, 4)


In [14]:
#reshaping using tf.reshape(matrix,dimensions)
reshaped_mat = tf.reshape(mat,(4,2))
print(reshaped_mat)
print('\n','Reshaped matrix shape: ',reshaped_mat.shape)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)

 Reshaped matrix shape:  (4, 2)


# Thank You
## Check out the BROADCASTING in next jupyter notebook