In [1]:
import tensorflow as tf
import numpy as np

# Tensor
Tensors are the multidimensional arrays with uniform type called as dtype. All the tensors are immutable like python strings and numbers. Tensors cannot be updated once created but can be created new onces.

In [2]:
#checking supported dtypes of tensorflow
print(tf.dtypes.DType)

<class 'tensorflow.python.framework.dtypes.DType'>


In [10]:
#Lets create some tensors
#All the things in tensorflow are tensors. Tensors are always matrices.
# Scalar is Rank-0 tensor

In [14]:
scalar = tf.constant(4) #This will be int32 dtype default
print(scalar)

tf.Tensor(4, shape=(), dtype=int32)


In [20]:
#A vector is rank-1 tensor
vector = tf.constant([1 ,2,3,4]) #default dtype-> int32
print(vector)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [18]:
#creating vector with dtype float16
vector16 = tf.constant([1,2,3,4] , dtype=tf.float16)
print(vector16)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float16)


In [22]:
# A matrix is rank-3 tensor
matrix = tf.constant([ [1,2,3] , [4,5,6] , [7,8,8]]) #int32
print(matrix)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 8]], shape=(3, 3), dtype=int32)
